# Generated by Django 4.2.13 on 2024-06-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
